def _help () :
    print ('------------------------- ADMIN ------------------------')
    print ('register - mendaftarkan pengguna baru')
    print ('carirarity - mencari gadget berdasarkan rarity tertentu')
    print ('caritahun - mencari gadget berdasarkan tahun ditemukan')
    print ('tambahitem - menambah item')
    print ('hapusitem - menghapus item')
    print ('ubahjumlah - mengubah jumlah gadget dan consumable')
    print ('riwayatpinjam - melihat riwayat peminjaman gadget')
    print ('riwayatkembali - melihat riwayat pengembalian gadget')
    print ('riwayatambil - melihat riwayat pengambilan consumable')
    print ('save - menyimpan data setelah diubah')
    print ('exit - keluar dari aplikasi')
    print ('--------------------------------------------------------')
    print ()
    print ('------------------------ USER --------------------------')
    print ('login - masuk ke aplikasi')
    print ('carirarity - mencari gadget berdasarkan rarity tertentu')
    print ('caritahun - mencari gadget berdasarkan tahun ditemukan')
    print ('pinjam - meminjam gadget')
    print ('kembalikan - mengembalikan gadget seutuhnya')
    print ('minta - meminta consumable yang tersedia')
    print ('save - menyimpan data setelah diubah')
    print ('exit - keluar dari aplikasi')
    print ('--------------------------------------------------------')